version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel
  postgres:
    image: postgres:13.3
    container_name: lepostgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ledatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - laravel
  pgadmin:
    image: dpage/pgadmin4:5.2
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - "pgadmin:/var/lib/pgadmin"
      - "./docker/servers.json:/pgadmin4/servers.json"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  pgadmin:
  postgres:
